;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Buildable.StructureType.Ceiling.Base",NewTagName="Buildable.StructureType.Ceiling.Standard")
+GameplayTagRedirects=(OldTagName="Buildable.StructureType.Foundation.Base",NewTagName="Buildable.StructureType.Foundation.Standard")
+GameplayTagRedirects=(OldTagName="Buildable.StructureType.Wall.Base",NewTagName="Buildable.StructureType.Wall.Standard")
+GameplayTagList=(Tag="Buildable.ResourceType",DevComment="")
+GameplayTagList=(Tag="Buildable.ResourceType.Metal",DevComment="")
+GameplayTagList=(Tag="Buildable.ResourceType.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.ResourceType.Wood",DevComment="")
+GameplayTagList=(Tag="Buildable.StructureType",DevComment="")
+GameplayTagList=(Tag="Buildable.StructureType.Ceiling",DevComment="")
+GameplayTagList=(Tag="Buildable.StructureType.Ceiling.Standard",DevComment="")
+GameplayTagList=(Tag="Buildable.StructureType.Foundation",DevComment="")
+GameplayTagList=(Tag="Buildable.StructureType.Foundation.Standard",DevComment="")
+GameplayTagList=(Tag="Buildable.StructureType.Wall",DevComment="")
+GameplayTagList=(Tag="Buildable.StructureType.Wall.Doorframe",DevComment="")
+GameplayTagList=(Tag="Buildable.StructureType.Wall.Standard",DevComment="")

